title: Alaaedin Yahyaoui Business Intelligence engineer  # your name (or website title) here
logo: "/images/alaaedin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 "Analyzing and visualizing data to make better and informed business decisions."
  <br><br>
  "Alaaedin is a versatile and highly analytical researcher, with wide ranging experience."
  <br>
  "Alaaedin is a versatile and highly analytical researcher, with wide ranging experience."
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My CV</a>
  <br><br>

