title: Alaaedin Yahyaoui - Business Intelligence engineer  # your name (or website title) here
logo: "/images/alaaedin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm passionate about Analyzing and visualizing data to make better and informed business decisions.
  <br><br>
  Alaaedin is a versatile and highly analytical researcher, with wide ranging experience including :
  <br>
  Data modeling, integration as well as reporting and visualisation, with an avid interest in business
  <br>
  intelligence looking for a challenging and varied role that provides ample opportunity to be creative and learn.
  <br>
  Proficient in SQL, Python, Excel, and data visualization tools such as Tableau, PowerBI and Google Data Studio
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My CV</a>
  <br><br>

